Support repeatable "node_json" and "node_yaml" options
itamae-kitchen/itamae pull request #351
Opened 2022-05-22 17:28 UTC by ineu

Thor supports two ways to pass mutiple values to a flag: via the :array type or via the "repeatable" option. This PR adds the latter.
It allows to pass multiple `node_yaml` and `node_json` files that will all be read and applied to a node.

The logic is as follows:
- Hashes are merged
- Scalars and arrays are overwritten

A common use case for this feature is applying vars to a group of nodes (compare to Ansible's `group_vars` and `host_vars`).

Example:
```sh
  itamae ssh --node-json vars/global.json --node-yaml group.yml --node-yaml node-1.yml recipes.rb
```

2022-05-23 01:59 UTC, unasuke approved these changes
I think it's good. After merging this, we should increment minor version, don't we? @sue445

2022-05-23 03:08 UTC, sue445 requested changes
@ineu `repeatable` option is available since thor v1.0.0+.
https://github.com/rails/thor/releases/tag/v1.0.0

Could you add `>= 1.0.0` to https://github.com/itamae-kitchen/itamae/blob/v1.12.6/itamae.gemspec#L29 ?

e.g. 

```ruby
spec.add_runtime_dependency "thor", ">= 1.0.0"
```

Others changes are LGTM

2022-05-23 07:48 UTC, ineu commented
Good point, I'll fix it.

Btw, should Ruby 2.3 still be supported? It has been deprecated for 6 years by now: https://endoflife.date/ruby
It's the default version in Ubuntu 16.04 LTS, but 18.04 LTS has 2.5

2022-05-23 09:14 UTC, unasuke commented
@ineu It's a sharp and interesting question for us.
Usually, no one uses ruby 2.3 now. But in the world of infrastructure as code, it's not surprising to use outdated instances like running ruby 2.3. Actually, specinfra which is the backend library of itamae, supports ruby 2.1.
And, Itamae has not specificated its support versions of ruby before now. If dropping support of eol-ed ruby, we should release a new major version.

related #292

2022-05-23 22:55 UTC, sue445 approved these changes
LGTM!

2022-05-23 22:55 UTC, merged

2022-05-24 12:22 UTC, sue445 commented
I published v1.13.0 🚀 

* https://github.com/itamae-kitchen/itamae/blob/master/CHANGELOG.md#v1130
* https://rubygems.org/gems/itamae/versions/1.13.0